# Generated by Django 4.0.5 on 2022-06-09 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='code',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='telephone_number',
            field=models.IntegerField(),
        ),
    ]
