# Generated by Django 4.0.5 on 2022-06-09 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_customer_code_alter_customer_telephone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='code',
            new_name='codeb',
        ),
    ]
