# Generated by Django 4.0.5 on 2022-06-09 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_code_customer_codeb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='codeb',
            new_name='code',
        ),
    ]
