# Generated by Django 4.0.5 on 2022-06-09 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_profile_telephone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='code',
            field=models.IntegerField(null=True),
        ),
    ]
