# Generated by Django 4.0.5 on 2022-06-10 19:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0009_alter_profile_code_alter_profile_employees_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_code', models.IntegerField(default=0)),
                ('code', models.IntegerField(default=0)),
                ('address', models.CharField(max_length=255)),
                ('turnover', models.IntegerField(default=0)),
                ('employees', models.IntegerField(default=0)),
                ('products', models.CharField(max_length=255)),
                ('sectors', models.CharField(max_length=255)),
                ('BOM_position', models.CharField(max_length=255)),
                ('linkedin_company', models.URLField()),
                ('email_company', models.EmailField(max_length=254)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('prefix', models.IntegerField(default=0)),
                ('number', models.IntegerField(default=0)),
                ('linkedin_user', models.URLField()),
                ('company', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('job_title', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
