# Generated by Django 4.0.5 on 2022-06-12 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_rename_profile_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrefixModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField()),
                ('prefix', models.IntegerField()),
            ],
        ),
    ]
