# Generated by Django 4.0.5 on 2022-06-12 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_prefixmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prefixmodel',
            name='id',
        ),
        migrations.AddField(
            model_name='prefixmodel',
            name='name',
            field=models.CharField(default='', max_length=255, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
