# Generated by Django 4.0.5 on 2022-06-12 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_alter_prefixmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prefixmodel',
            name='image',
            field=models.ImageField(storage='static/img/user_prefix_model/', unique=True, upload_to=''),
        ),
    ]
