# Generated by Django 4.0.5 on 2022-06-12 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_alter_prefixmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prefixmodel',
            name='image',
            field=models.ImageField(unique=True, upload_to='static/img/user_prefix_model/'),
        ),
    ]
