# Generated by Django 4.0.5 on 2022-06-12 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_alter_prefixmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prefixmodel',
            name='image',
            field=models.URLField(),
        ),
    ]
